### ISSUE TITLE
How do I run your project successfully?

### ISSUE THREAD

**Issue by vtn98** [Prem95/face-liveness-detector#2]
Hi @Prem95,
I tried to run your project, but it misses file: mb1_120x120.yml.
Can you provide it for testing? 
Thank you!

**Comment by Prem95** [comment]
> Hi @Prem95,
> I tried to run your project, but it misses file: mb1_120x120.yml.
> Can you provide it for testing?
> Thank you!

Hi there! Thanks for reporting this. I might have missed out on some of the build files. I have added the files.
[Commit](https://github.com/Prem95/face-liveness-detector/commit/c3634144b69344fc79f0c787b4bfd329a80bc460)

**Comment by vtn98** [comment]
thanks, but I have this problem:
No such file or directory: 'face_det/weights/mb1_120x120.pth'

**Comment by Prem95** [comment]
Hi there!  Thank you so much for reporting this. It seems like I have again ignored the files. 

Please try now. It has been added. [Commit](https://github.com/Prem95/face-liveness-detector/commit/0a14a4739725bf0bbf17ba147816d1851487ea8f)
