### ISSUE TITLE
No module named 'FaceBoxes.utils.nms.cpu_nms'

### ISSUE THREAD

**Issue by neonn0d** [Prem95/face-liveness-detector#3]
Hi there I'm having this issue 
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from utility.video_utils import VideoUtils
  File "C:\Users\hyper\OneDrive\Desktop\face-liveness-detector\utility\video_utils.py", line 9, in <module>
    from face_detector import FaceDetector
  File "C:\Users\hyper\OneDrive\Desktop\face-liveness-detector\face_detector.py", line 7, in <module>
    from FaceBoxes import FaceBoxes
  File "face_det\FaceBoxes\__init__.py", line 1, in <module>
    from .FaceBoxes import FaceBoxes
  File "face_det\FaceBoxes\FaceBoxes.py", line 10, in <module>
    from .utils.nms_wrapper import nms
  File "face_det\FaceBoxes\utils\nms_wrapper.py", line 10, in <module>
    from .nms.cpu_nms import cpu_nms, cpu_soft_nms
ModuleNotFoundError: No module named 'FaceBoxes.utils.nms.cpu_nms'
```

OS : Windows 11
Python Version 3.8.4

**Comment by Prem95** [comment]
Hi @neonn0d,

This error will be reported if the face_det is not built. You can manually build it again by running `sh build.sh` in face_det module.

Please let me know if the problem persists. Thank you.

**Comment by Prem95** [comment]
Hi, is this issue solved on your end? Thank you.

**Comment by akarshsoman** [comment]
@Prem95 I'm getting the same error when trying to install on windows , i want to know if i can use any other face detection module rather this face_det. and then pass it to classifier model

**Comment by Prem95** [comment]
Hi @neonn0d, it seems like you would need to install other external dependencies to run it on Windows (since Windows does not support sh). You can take a look here [StackOverFlow](https://stackoverflow.com/questions/26522789/how-to-run-sh-on-windows-command-prompt)

**Comment by Prem95** [comment]
> @Prem95 I'm getting the same error when trying to install on windows, i want to know if I can use any other face detection module rather than this **face_det**. and then pass it to the classifier model

Sorry, but I am not aware of any face detection model out there except for the one I am using right now. Probably there might be some library that is able to provide the face bounding box. Thanks!

**Comment by akarshsoman** [comment]
@Prem95 i was thinking of using mtcnn or mediapipe face detection models.

**Comment by Prem95** [comment]
> @Prem95 i was thinking of using mtcnn or mediapipe face detection models.

Mediapipe seems like a good solution. All you need is the bounding box coordinates of the face and it should be good to go!
