### ISSUE TITLE
How to run it on windows

### ISSUE THREAD

**Issue by akarshsoman** [Prem95/face-liveness-detector#4]
can you please tell me how i can run it on windows? since sh wont work on windows

**Comment by Prem95** [comment]
Hi there! By default, Windows uses a different syntax to execute commands (.exe). Instead, you'll need to install a third-party tool such as [Cygwin](http://www.cygwin.com/).

Or another way would be to install Github for Windows. You can refer [here](https://superuser.com/questions/120045/how-to-execute-sh-file-on-windows).

**Comment by Prem95** [comment]
Closing issue.

**Comment by anhky** [comment]
I get an error like this? Can you help me?
![image](https://user-images.githubusercontent.com/44550009/144964507-0bff5baf-8b6e-4b8a-9ec2-f7bd9bd0fc20.png)
